version: '3.8'

services:
  # Service de développement
  dev:
    build:
      context: .
      target: build-stage
    ports:
      - '5173:5173'
    volumes:
      - .:/app
      - /app/node_modules
    command: pnpm dev --host 0.0.0.0
    environment:
      - VITE_HOST=0.0.0.0
      - NODE_ENV=development
    networks:
      - kata-network

  # Service de production
  prod:
    build:
      context: .
      target: production-stage
    ports:
      - '80:80'
    environment:
      - NODE_ENV=production
    networks:
      - kata-network

networks:
  kata-network:
    driver: bridge
